/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalysRouteImport } from './routes/analys'
import { Route as BokningsassistentRouteImport } from './routes/bokningsassistent'
import { Route as BokningsreglerRouteImport } from './routes/bokningsregler'
import { Route as BordsplaceringRouteImport } from './routes/bordsplacering'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as EpostagentRouteImport } from './routes/epostagent'
import { Route as GastinsiktRouteImport } from './routes/gastinsikt'
import { Route as HotellRouteImport } from './routes/hotell'
import { Route as KampanjerRouteImport } from './routes/kampanjer'
import { Route as RestaurangRouteImport } from './routes/restaurang'
import { Route as SalsplanRouteImport } from './routes/salsplan'
import { Route as TillganglighetRouteImport } from './routes/tillganglighet'
import { Route as VoiceAgentRouteImport } from './routes/voice-agent'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAnalysRouteImport } from './routes/dashboard.analys'
import { Route as DashboardGasterRouteImport } from './routes/dashboard.gaster'
import { Route as DashboardInkorgRouteImport } from './routes/dashboard.inkorg'
import { Route as DashboardSalsplanRouteImport } from './routes/dashboard.salsplan'
import { Route as ForetagKarriarRouteImport } from './routes/foretag.karriar'
import { Route as ForetagKontaktRouteImport } from './routes/foretag.kontakt'
import { Route as ForetagOmOssRouteImport } from './routes/foretag.om-oss'
import { Route as ForetagPartnersRouteImport } from './routes/foretag.partners'
import { Route as ForetagSakerhetRouteImport } from './routes/foretag.sakerhet'
import { Route as LosningarBarerOchLoungerRouteImport } from './routes/losningar.barer-och-lounger'
import { Route as LosningarFineDiningRouteImport } from './routes/losningar.fine-dining'
import { Route as LosningarFristaendeRestaurangerRouteImport } from './routes/losningar.fristaende-restauranger'
import { Route as LosningarHogvolymsverksamheterRouteImport } from './routes/losningar.hogvolymsverksamheter'
import { Route as LosningarHotellRouteImport } from './routes/losningar.hotell'
import { Route as LosningarRestauranggrupperRouteImport } from './routes/losningar.restauranggrupper'
import { Route as ResurserApiRouteImport } from './routes/resurser.api'
import { Route as ResurserGuiderRouteImport } from './routes/resurser.guider'
import { Route as ResurserHjalpcenterRouteImport } from './routes/resurser.hjalpcenter'
import { Route as ResurserInsikterRouteImport } from './routes/resurser.insikter'
import { Route as ResurserKundberattelserRouteImport } from './routes/resurser.kundberattelser'
import { Route as ResurserProduktnyheterRouteImport } from './routes/resurser.produktnyheter'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysRoute = AnalysRouteImport.update({
  id: '/analys',
  path: '/analys',
  getParentRoute: () => rootRouteImport,
} as any)
const BokningsassistentRoute = BokningsassistentRouteImport.update({
  id: '/bokningsassistent',
  path: '/bokningsassistent',
  getParentRoute: () => rootRouteImport,
} as any)
const BokningsreglerRoute = BokningsreglerRouteImport.update({
  id: '/bokningsregler',
  path: '/bokningsregler',
  getParentRoute: () => rootRouteImport,
} as any)
const BordsplaceringRoute = BordsplaceringRouteImport.update({
  id: '/bordsplacering',
  path: '/bordsplacering',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const EpostagentRoute = EpostagentRouteImport.update({
  id: '/epostagent',
  path: '/epostagent',
  getParentRoute: () => rootRouteImport,
} as any)
const GastinsiktRoute = GastinsiktRouteImport.update({
  id: '/gastinsikt',
  path: '/gastinsikt',
  getParentRoute: () => rootRouteImport,
} as any)
const HotellRoute = HotellRouteImport.update({
  id: '/hotell',
  path: '/hotell',
  getParentRoute: () => rootRouteImport,
} as any)
const KampanjerRoute = KampanjerRouteImport.update({
  id: '/kampanjer',
  path: '/kampanjer',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurangRoute = RestaurangRouteImport.update({
  id: '/restaurang',
  path: '/restaurang',
  getParentRoute: () => rootRouteImport,
} as any)
const SalsplanRoute = SalsplanRouteImport.update({
  id: '/salsplan',
  path: '/salsplan',
  getParentRoute: () => rootRouteImport,
} as any)
const TillganglighetRoute = TillganglighetRouteImport.update({
  id: '/tillganglighet',
  path: '/tillganglighet',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceAgentRoute = VoiceAgentRouteImport.update({
  id: '/voice-agent',
  path: '/voice-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalysRoute = DashboardAnalysRouteImport.update({
  id: '/analys',
  path: '/analys',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGasterRoute = DashboardGasterRouteImport.update({
  id: '/gaster',
  path: '/gaster',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInkorgRoute = DashboardInkorgRouteImport.update({
  id: '/inkorg',
  path: '/inkorg',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSalsplanRoute = DashboardSalsplanRouteImport.update({
  id: '/salsplan',
  path: '/salsplan',
  getParentRoute: () => DashboardRoute,
} as any)
const ForetagKarriarRoute = ForetagKarriarRouteImport.update({
  id: '/foretag/karriar',
  path: '/foretag/karriar',
  getParentRoute: () => rootRouteImport,
} as any)
const ForetagKontaktRoute = ForetagKontaktRouteImport.update({
  id: '/foretag/kontakt',
  path: '/foretag/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const ForetagOmOssRoute = ForetagOmOssRouteImport.update({
  id: '/foretag/om-oss',
  path: '/foretag/om-oss',
  getParentRoute: () => rootRouteImport,
} as any)
const ForetagPartnersRoute = ForetagPartnersRouteImport.update({
  id: '/foretag/partners',
  path: '/foretag/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const ForetagSakerhetRoute = ForetagSakerhetRouteImport.update({
  id: '/foretag/sakerhet',
  path: '/foretag/sakerhet',
  getParentRoute: () => rootRouteImport,
} as any)
const LosningarBarerOchLoungerRoute =
  LosningarBarerOchLoungerRouteImport.update({
    id: '/losningar/barer-och-lounger',
    path: '/losningar/barer-och-lounger',
    getParentRoute: () => rootRouteImport,
  } as any)
const LosningarFineDiningRoute = LosningarFineDiningRouteImport.update({
  id: '/losningar/fine-dining',
  path: '/losningar/fine-dining',
  getParentRoute: () => rootRouteImport,
} as any)
const LosningarFristaendeRestaurangerRoute =
  LosningarFristaendeRestaurangerRouteImport.update({
    id: '/losningar/fristaende-restauranger',
    path: '/losningar/fristaende-restauranger',
    getParentRoute: () => rootRouteImport,
  } as any)
const LosningarHogvolymsverksamheterRoute =
  LosningarHogvolymsverksamheterRouteImport.update({
    id: '/losningar/hogvolymsverksamheter',
    path: '/losningar/hogvolymsverksamheter',
    getParentRoute: () => rootRouteImport,
  } as any)
const LosningarHotellRoute = LosningarHotellRouteImport.update({
  id: '/losningar/hotell',
  path: '/losningar/hotell',
  getParentRoute: () => rootRouteImport,
} as any)
const LosningarRestauranggrupperRoute =
  LosningarRestauranggrupperRouteImport.update({
    id: '/losningar/restauranggrupper',
    path: '/losningar/restauranggrupper',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResurserApiRoute = ResurserApiRouteImport.update({
  id: '/resurser/api',
  path: '/resurser/api',
  getParentRoute: () => rootRouteImport,
} as any)
const ResurserGuiderRoute = ResurserGuiderRouteImport.update({
  id: '/resurser/guider',
  path: '/resurser/guider',
  getParentRoute: () => rootRouteImport,
} as any)
const ResurserHjalpcenterRoute = ResurserHjalpcenterRouteImport.update({
  id: '/resurser/hjalpcenter',
  path: '/resurser/hjalpcenter',
  getParentRoute: () => rootRouteImport,
} as any)
const ResurserInsikterRoute = ResurserInsikterRouteImport.update({
  id: '/resurser/insikter',
  path: '/resurser/insikter',
  getParentRoute: () => rootRouteImport,
} as any)
const ResurserKundberattelserRoute = ResurserKundberattelserRouteImport.update({
  id: '/resurser/kundberattelser',
  path: '/resurser/kundberattelser',
  getParentRoute: () => rootRouteImport,
} as any)
const ResurserProduktnyheterRoute = ResurserProduktnyheterRouteImport.update({
  id: '/resurser/produktnyheter',
  path: '/resurser/produktnyheter',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analys': typeof AnalysRoute
  '/bokningsassistent': typeof BokningsassistentRoute
  '/bokningsregler': typeof BokningsreglerRoute
  '/bordsplacering': typeof BordsplaceringRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo': typeof DemoRoute
  '/epostagent': typeof EpostagentRoute
  '/gastinsikt': typeof GastinsiktRoute
  '/hotell': typeof HotellRoute
  '/kampanjer': typeof KampanjerRoute
  '/restaurang': typeof RestaurangRoute
  '/salsplan': typeof SalsplanRoute
  '/tillganglighet': typeof TillganglighetRoute
  '/voice-agent': typeof VoiceAgentRoute
  '/dashboard/analys': typeof DashboardAnalysRoute
  '/dashboard/gaster': typeof DashboardGasterRoute
  '/dashboard/inkorg': typeof DashboardInkorgRoute
  '/dashboard/salsplan': typeof DashboardSalsplanRoute
  '/foretag/karriar': typeof ForetagKarriarRoute
  '/foretag/kontakt': typeof ForetagKontaktRoute
  '/foretag/om-oss': typeof ForetagOmOssRoute
  '/foretag/partners': typeof ForetagPartnersRoute
  '/foretag/sakerhet': typeof ForetagSakerhetRoute
  '/losningar/barer-och-lounger': typeof LosningarBarerOchLoungerRoute
  '/losningar/fine-dining': typeof LosningarFineDiningRoute
  '/losningar/fristaende-restauranger': typeof LosningarFristaendeRestaurangerRoute
  '/losningar/hogvolymsverksamheter': typeof LosningarHogvolymsverksamheterRoute
  '/losningar/hotell': typeof LosningarHotellRoute
  '/losningar/restauranggrupper': typeof LosningarRestauranggrupperRoute
  '/resurser/api': typeof ResurserApiRoute
  '/resurser/guider': typeof ResurserGuiderRoute
  '/resurser/hjalpcenter': typeof ResurserHjalpcenterRoute
  '/resurser/insikter': typeof ResurserInsikterRoute
  '/resurser/kundberattelser': typeof ResurserKundberattelserRoute
  '/resurser/produktnyheter': typeof ResurserProduktnyheterRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analys': typeof AnalysRoute
  '/bokningsassistent': typeof BokningsassistentRoute
  '/bokningsregler': typeof BokningsreglerRoute
  '/bordsplacering': typeof BordsplaceringRoute
  '/demo': typeof DemoRoute
  '/epostagent': typeof EpostagentRoute
  '/gastinsikt': typeof GastinsiktRoute
  '/hotell': typeof HotellRoute
  '/kampanjer': typeof KampanjerRoute
  '/restaurang': typeof RestaurangRoute
  '/salsplan': typeof SalsplanRoute
  '/tillganglighet': typeof TillganglighetRoute
  '/voice-agent': typeof VoiceAgentRoute
  '/dashboard/analys': typeof DashboardAnalysRoute
  '/dashboard/gaster': typeof DashboardGasterRoute
  '/dashboard/inkorg': typeof DashboardInkorgRoute
  '/dashboard/salsplan': typeof DashboardSalsplanRoute
  '/foretag/karriar': typeof ForetagKarriarRoute
  '/foretag/kontakt': typeof ForetagKontaktRoute
  '/foretag/om-oss': typeof ForetagOmOssRoute
  '/foretag/partners': typeof ForetagPartnersRoute
  '/foretag/sakerhet': typeof ForetagSakerhetRoute
  '/losningar/barer-och-lounger': typeof LosningarBarerOchLoungerRoute
  '/losningar/fine-dining': typeof LosningarFineDiningRoute
  '/losningar/fristaende-restauranger': typeof LosningarFristaendeRestaurangerRoute
  '/losningar/hogvolymsverksamheter': typeof LosningarHogvolymsverksamheterRoute
  '/losningar/hotell': typeof LosningarHotellRoute
  '/losningar/restauranggrupper': typeof LosningarRestauranggrupperRoute
  '/resurser/api': typeof ResurserApiRoute
  '/resurser/guider': typeof ResurserGuiderRoute
  '/resurser/hjalpcenter': typeof ResurserHjalpcenterRoute
  '/resurser/insikter': typeof ResurserInsikterRoute
  '/resurser/kundberattelser': typeof ResurserKundberattelserRoute
  '/resurser/produktnyheter': typeof ResurserProduktnyheterRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analys': typeof AnalysRoute
  '/bokningsassistent': typeof BokningsassistentRoute
  '/bokningsregler': typeof BokningsreglerRoute
  '/bordsplacering': typeof BordsplaceringRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo': typeof DemoRoute
  '/epostagent': typeof EpostagentRoute
  '/gastinsikt': typeof GastinsiktRoute
  '/hotell': typeof HotellRoute
  '/kampanjer': typeof KampanjerRoute
  '/restaurang': typeof RestaurangRoute
  '/salsplan': typeof SalsplanRoute
  '/tillganglighet': typeof TillganglighetRoute
  '/voice-agent': typeof VoiceAgentRoute
  '/dashboard/analys': typeof DashboardAnalysRoute
  '/dashboard/gaster': typeof DashboardGasterRoute
  '/dashboard/inkorg': typeof DashboardInkorgRoute
  '/dashboard/salsplan': typeof DashboardSalsplanRoute
  '/foretag/karriar': typeof ForetagKarriarRoute
  '/foretag/kontakt': typeof ForetagKontaktRoute
  '/foretag/om-oss': typeof ForetagOmOssRoute
  '/foretag/partners': typeof ForetagPartnersRoute
  '/foretag/sakerhet': typeof ForetagSakerhetRoute
  '/losningar/barer-och-lounger': typeof LosningarBarerOchLoungerRoute
  '/losningar/fine-dining': typeof LosningarFineDiningRoute
  '/losningar/fristaende-restauranger': typeof LosningarFristaendeRestaurangerRoute
  '/losningar/hogvolymsverksamheter': typeof LosningarHogvolymsverksamheterRoute
  '/losningar/hotell': typeof LosningarHotellRoute
  '/losningar/restauranggrupper': typeof LosningarRestauranggrupperRoute
  '/resurser/api': typeof ResurserApiRoute
  '/resurser/guider': typeof ResurserGuiderRoute
  '/resurser/hjalpcenter': typeof ResurserHjalpcenterRoute
  '/resurser/insikter': typeof ResurserInsikterRoute
  '/resurser/kundberattelser': typeof ResurserKundberattelserRoute
  '/resurser/produktnyheter': typeof ResurserProduktnyheterRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analys'
    | '/bokningsassistent'
    | '/bokningsregler'
    | '/bordsplacering'
    | '/dashboard'
    | '/demo'
    | '/epostagent'
    | '/gastinsikt'
    | '/hotell'
    | '/kampanjer'
    | '/restaurang'
    | '/salsplan'
    | '/tillganglighet'
    | '/voice-agent'
    | '/dashboard/analys'
    | '/dashboard/gaster'
    | '/dashboard/inkorg'
    | '/dashboard/salsplan'
    | '/foretag/karriar'
    | '/foretag/kontakt'
    | '/foretag/om-oss'
    | '/foretag/partners'
    | '/foretag/sakerhet'
    | '/losningar/barer-och-lounger'
    | '/losningar/fine-dining'
    | '/losningar/fristaende-restauranger'
    | '/losningar/hogvolymsverksamheter'
    | '/losningar/hotell'
    | '/losningar/restauranggrupper'
    | '/resurser/api'
    | '/resurser/guider'
    | '/resurser/hjalpcenter'
    | '/resurser/insikter'
    | '/resurser/kundberattelser'
    | '/resurser/produktnyheter'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analys'
    | '/bokningsassistent'
    | '/bokningsregler'
    | '/bordsplacering'
    | '/demo'
    | '/epostagent'
    | '/gastinsikt'
    | '/hotell'
    | '/kampanjer'
    | '/restaurang'
    | '/salsplan'
    | '/tillganglighet'
    | '/voice-agent'
    | '/dashboard/analys'
    | '/dashboard/gaster'
    | '/dashboard/inkorg'
    | '/dashboard/salsplan'
    | '/foretag/karriar'
    | '/foretag/kontakt'
    | '/foretag/om-oss'
    | '/foretag/partners'
    | '/foretag/sakerhet'
    | '/losningar/barer-och-lounger'
    | '/losningar/fine-dining'
    | '/losningar/fristaende-restauranger'
    | '/losningar/hogvolymsverksamheter'
    | '/losningar/hotell'
    | '/losningar/restauranggrupper'
    | '/resurser/api'
    | '/resurser/guider'
    | '/resurser/hjalpcenter'
    | '/resurser/insikter'
    | '/resurser/kundberattelser'
    | '/resurser/produktnyheter'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/analys'
    | '/bokningsassistent'
    | '/bokningsregler'
    | '/bordsplacering'
    | '/dashboard'
    | '/demo'
    | '/epostagent'
    | '/gastinsikt'
    | '/hotell'
    | '/kampanjer'
    | '/restaurang'
    | '/salsplan'
    | '/tillganglighet'
    | '/voice-agent'
    | '/dashboard/analys'
    | '/dashboard/gaster'
    | '/dashboard/inkorg'
    | '/dashboard/salsplan'
    | '/foretag/karriar'
    | '/foretag/kontakt'
    | '/foretag/om-oss'
    | '/foretag/partners'
    | '/foretag/sakerhet'
    | '/losningar/barer-och-lounger'
    | '/losningar/fine-dining'
    | '/losningar/fristaende-restauranger'
    | '/losningar/hogvolymsverksamheter'
    | '/losningar/hotell'
    | '/losningar/restauranggrupper'
    | '/resurser/api'
    | '/resurser/guider'
    | '/resurser/hjalpcenter'
    | '/resurser/insikter'
    | '/resurser/kundberattelser'
    | '/resurser/produktnyheter'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysRoute: typeof AnalysRoute
  BokningsassistentRoute: typeof BokningsassistentRoute
  BokningsreglerRoute: typeof BokningsreglerRoute
  BordsplaceringRoute: typeof BordsplaceringRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DemoRoute: typeof DemoRoute
  EpostagentRoute: typeof EpostagentRoute
  GastinsiktRoute: typeof GastinsiktRoute
  HotellRoute: typeof HotellRoute
  KampanjerRoute: typeof KampanjerRoute
  RestaurangRoute: typeof RestaurangRoute
  SalsplanRoute: typeof SalsplanRoute
  TillganglighetRoute: typeof TillganglighetRoute
  VoiceAgentRoute: typeof VoiceAgentRoute
  ForetagKarriarRoute: typeof ForetagKarriarRoute
  ForetagKontaktRoute: typeof ForetagKontaktRoute
  ForetagOmOssRoute: typeof ForetagOmOssRoute
  ForetagPartnersRoute: typeof ForetagPartnersRoute
  ForetagSakerhetRoute: typeof ForetagSakerhetRoute
  LosningarBarerOchLoungerRoute: typeof LosningarBarerOchLoungerRoute
  LosningarFineDiningRoute: typeof LosningarFineDiningRoute
  LosningarFristaendeRestaurangerRoute: typeof LosningarFristaendeRestaurangerRoute
  LosningarHogvolymsverksamheterRoute: typeof LosningarHogvolymsverksamheterRoute
  LosningarHotellRoute: typeof LosningarHotellRoute
  LosningarRestauranggrupperRoute: typeof LosningarRestauranggrupperRoute
  ResurserApiRoute: typeof ResurserApiRoute
  ResurserGuiderRoute: typeof ResurserGuiderRoute
  ResurserHjalpcenterRoute: typeof ResurserHjalpcenterRoute
  ResurserInsikterRoute: typeof ResurserInsikterRoute
  ResurserKundberattelserRoute: typeof ResurserKundberattelserRoute
  ResurserProduktnyheterRoute: typeof ResurserProduktnyheterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analys': {
      id: '/analys'
      path: '/analys'
      fullPath: '/analys'
      preLoaderRoute: typeof AnalysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bokningsassistent': {
      id: '/bokningsassistent'
      path: '/bokningsassistent'
      fullPath: '/bokningsassistent'
      preLoaderRoute: typeof BokningsassistentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bokningsregler': {
      id: '/bokningsregler'
      path: '/bokningsregler'
      fullPath: '/bokningsregler'
      preLoaderRoute: typeof BokningsreglerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bordsplacering': {
      id: '/bordsplacering'
      path: '/bordsplacering'
      fullPath: '/bordsplacering'
      preLoaderRoute: typeof BordsplaceringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epostagent': {
      id: '/epostagent'
      path: '/epostagent'
      fullPath: '/epostagent'
      preLoaderRoute: typeof EpostagentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gastinsikt': {
      id: '/gastinsikt'
      path: '/gastinsikt'
      fullPath: '/gastinsikt'
      preLoaderRoute: typeof GastinsiktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotell': {
      id: '/hotell'
      path: '/hotell'
      fullPath: '/hotell'
      preLoaderRoute: typeof HotellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kampanjer': {
      id: '/kampanjer'
      path: '/kampanjer'
      fullPath: '/kampanjer'
      preLoaderRoute: typeof KampanjerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurang': {
      id: '/restaurang'
      path: '/restaurang'
      fullPath: '/restaurang'
      preLoaderRoute: typeof RestaurangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salsplan': {
      id: '/salsplan'
      path: '/salsplan'
      fullPath: '/salsplan'
      preLoaderRoute: typeof SalsplanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tillganglighet': {
      id: '/tillganglighet'
      path: '/tillganglighet'
      fullPath: '/tillganglighet'
      preLoaderRoute: typeof TillganglighetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice-agent': {
      id: '/voice-agent'
      path: '/voice-agent'
      fullPath: '/voice-agent'
      preLoaderRoute: typeof VoiceAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analys': {
      id: '/dashboard/analys'
      path: '/analys'
      fullPath: '/dashboard/analys'
      preLoaderRoute: typeof DashboardAnalysRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/gaster': {
      id: '/dashboard/gaster'
      path: '/gaster'
      fullPath: '/dashboard/gaster'
      preLoaderRoute: typeof DashboardGasterRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inkorg': {
      id: '/dashboard/inkorg'
      path: '/inkorg'
      fullPath: '/dashboard/inkorg'
      preLoaderRoute: typeof DashboardInkorgRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/salsplan': {
      id: '/dashboard/salsplan'
      path: '/salsplan'
      fullPath: '/dashboard/salsplan'
      preLoaderRoute: typeof DashboardSalsplanRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/foretag/karriar': {
      id: '/foretag/karriar'
      path: '/foretag/karriar'
      fullPath: '/foretag/karriar'
      preLoaderRoute: typeof ForetagKarriarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foretag/kontakt': {
      id: '/foretag/kontakt'
      path: '/foretag/kontakt'
      fullPath: '/foretag/kontakt'
      preLoaderRoute: typeof ForetagKontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foretag/om-oss': {
      id: '/foretag/om-oss'
      path: '/foretag/om-oss'
      fullPath: '/foretag/om-oss'
      preLoaderRoute: typeof ForetagOmOssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foretag/partners': {
      id: '/foretag/partners'
      path: '/foretag/partners'
      fullPath: '/foretag/partners'
      preLoaderRoute: typeof ForetagPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foretag/sakerhet': {
      id: '/foretag/sakerhet'
      path: '/foretag/sakerhet'
      fullPath: '/foretag/sakerhet'
      preLoaderRoute: typeof ForetagSakerhetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/losningar/barer-och-lounger': {
      id: '/losningar/barer-och-lounger'
      path: '/losningar/barer-och-lounger'
      fullPath: '/losningar/barer-och-lounger'
      preLoaderRoute: typeof LosningarBarerOchLoungerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/losningar/fine-dining': {
      id: '/losningar/fine-dining'
      path: '/losningar/fine-dining'
      fullPath: '/losningar/fine-dining'
      preLoaderRoute: typeof LosningarFineDiningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/losningar/fristaende-restauranger': {
      id: '/losningar/fristaende-restauranger'
      path: '/losningar/fristaende-restauranger'
      fullPath: '/losningar/fristaende-restauranger'
      preLoaderRoute: typeof LosningarFristaendeRestaurangerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/losningar/hogvolymsverksamheter': {
      id: '/losningar/hogvolymsverksamheter'
      path: '/losningar/hogvolymsverksamheter'
      fullPath: '/losningar/hogvolymsverksamheter'
      preLoaderRoute: typeof LosningarHogvolymsverksamheterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/losningar/hotell': {
      id: '/losningar/hotell'
      path: '/losningar/hotell'
      fullPath: '/losningar/hotell'
      preLoaderRoute: typeof LosningarHotellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/losningar/restauranggrupper': {
      id: '/losningar/restauranggrupper'
      path: '/losningar/restauranggrupper'
      fullPath: '/losningar/restauranggrupper'
      preLoaderRoute: typeof LosningarRestauranggrupperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resurser/api': {
      id: '/resurser/api'
      path: '/resurser/api'
      fullPath: '/resurser/api'
      preLoaderRoute: typeof ResurserApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resurser/guider': {
      id: '/resurser/guider'
      path: '/resurser/guider'
      fullPath: '/resurser/guider'
      preLoaderRoute: typeof ResurserGuiderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resurser/hjalpcenter': {
      id: '/resurser/hjalpcenter'
      path: '/resurser/hjalpcenter'
      fullPath: '/resurser/hjalpcenter'
      preLoaderRoute: typeof ResurserHjalpcenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resurser/insikter': {
      id: '/resurser/insikter'
      path: '/resurser/insikter'
      fullPath: '/resurser/insikter'
      preLoaderRoute: typeof ResurserInsikterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resurser/kundberattelser': {
      id: '/resurser/kundberattelser'
      path: '/resurser/kundberattelser'
      fullPath: '/resurser/kundberattelser'
      preLoaderRoute: typeof ResurserKundberattelserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resurser/produktnyheter': {
      id: '/resurser/produktnyheter'
      path: '/resurser/produktnyheter'
      fullPath: '/resurser/produktnyheter'
      preLoaderRoute: typeof ResurserProduktnyheterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalysRoute: typeof DashboardAnalysRoute
  DashboardGasterRoute: typeof DashboardGasterRoute
  DashboardInkorgRoute: typeof DashboardInkorgRoute
  DashboardSalsplanRoute: typeof DashboardSalsplanRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalysRoute: DashboardAnalysRoute,
  DashboardGasterRoute: DashboardGasterRoute,
  DashboardInkorgRoute: DashboardInkorgRoute,
  DashboardSalsplanRoute: DashboardSalsplanRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysRoute: AnalysRoute,
  BokningsassistentRoute: BokningsassistentRoute,
  BokningsreglerRoute: BokningsreglerRoute,
  BordsplaceringRoute: BordsplaceringRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DemoRoute: DemoRoute,
  EpostagentRoute: EpostagentRoute,
  GastinsiktRoute: GastinsiktRoute,
  HotellRoute: HotellRoute,
  KampanjerRoute: KampanjerRoute,
  RestaurangRoute: RestaurangRoute,
  SalsplanRoute: SalsplanRoute,
  TillganglighetRoute: TillganglighetRoute,
  VoiceAgentRoute: VoiceAgentRoute,
  ForetagKarriarRoute: ForetagKarriarRoute,
  ForetagKontaktRoute: ForetagKontaktRoute,
  ForetagOmOssRoute: ForetagOmOssRoute,
  ForetagPartnersRoute: ForetagPartnersRoute,
  ForetagSakerhetRoute: ForetagSakerhetRoute,
  LosningarBarerOchLoungerRoute: LosningarBarerOchLoungerRoute,
  LosningarFineDiningRoute: LosningarFineDiningRoute,
  LosningarFristaendeRestaurangerRoute: LosningarFristaendeRestaurangerRoute,
  LosningarHogvolymsverksamheterRoute: LosningarHogvolymsverksamheterRoute,
  LosningarHotellRoute: LosningarHotellRoute,
  LosningarRestauranggrupperRoute: LosningarRestauranggrupperRoute,
  ResurserApiRoute: ResurserApiRoute,
  ResurserGuiderRoute: ResurserGuiderRoute,
  ResurserHjalpcenterRoute: ResurserHjalpcenterRoute,
  ResurserInsikterRoute: ResurserInsikterRoute,
  ResurserKundberattelserRoute: ResurserKundberattelserRoute,
  ResurserProduktnyheterRoute: ResurserProduktnyheterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
