/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalysRouteImport } from './routes/analys'
import { Route as BokningsassistentRouteImport } from './routes/bokningsassistent'
import { Route as BokningsreglerRouteImport } from './routes/bokningsregler'
import { Route as BordsplaceringRouteImport } from './routes/bordsplacering'
import { Route as EpostagentRouteImport } from './routes/epostagent'
import { Route as GastinsiktRouteImport } from './routes/gastinsikt'
import { Route as KampanjerRouteImport } from './routes/kampanjer'
import { Route as SalsplanRouteImport } from './routes/salsplan'
import { Route as TillganglighetRouteImport } from './routes/tillganglighet'
import { Route as VoiceAgentRouteImport } from './routes/voice-agent'
import { Route as LosningarBarerOchLoungerRouteImport } from './routes/losningar.barer-och-lounger'
import { Route as LosningarFineDiningRouteImport } from './routes/losningar.fine-dining'
import { Route as LosningarFristaendeRestaurangerRouteImport } from './routes/losningar.fristaende-restauranger'
import { Route as LosningarHogvolymsverksamheterRouteImport } from './routes/losningar.hogvolymsverksamheter'
import { Route as LosningarHotellRouteImport } from './routes/losningar.hotell'
import { Route as LosningarRestauranggrupperRouteImport } from './routes/losningar.restauranggrupper'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysRoute = AnalysRouteImport.update({
  id: '/analys',
  path: '/analys',
  getParentRoute: () => rootRouteImport,
} as any)
const BokningsassistentRoute = BokningsassistentRouteImport.update({
  id: '/bokningsassistent',
  path: '/bokningsassistent',
  getParentRoute: () => rootRouteImport,
} as any)
const BokningsreglerRoute = BokningsreglerRouteImport.update({
  id: '/bokningsregler',
  path: '/bokningsregler',
  getParentRoute: () => rootRouteImport,
} as any)
const BordsplaceringRoute = BordsplaceringRouteImport.update({
  id: '/bordsplacering',
  path: '/bordsplacering',
  getParentRoute: () => rootRouteImport,
} as any)
const EpostagentRoute = EpostagentRouteImport.update({
  id: '/epostagent',
  path: '/epostagent',
  getParentRoute: () => rootRouteImport,
} as any)
const GastinsiktRoute = GastinsiktRouteImport.update({
  id: '/gastinsikt',
  path: '/gastinsikt',
  getParentRoute: () => rootRouteImport,
} as any)
const KampanjerRoute = KampanjerRouteImport.update({
  id: '/kampanjer',
  path: '/kampanjer',
  getParentRoute: () => rootRouteImport,
} as any)
const SalsplanRoute = SalsplanRouteImport.update({
  id: '/salsplan',
  path: '/salsplan',
  getParentRoute: () => rootRouteImport,
} as any)
const TillganglighetRoute = TillganglighetRouteImport.update({
  id: '/tillganglighet',
  path: '/tillganglighet',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceAgentRoute = VoiceAgentRouteImport.update({
  id: '/voice-agent',
  path: '/voice-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const LosningarBarerOchLoungerRoute =
  LosningarBarerOchLoungerRouteImport.update({
    id: '/losningar/barer-och-lounger',
    path: '/losningar/barer-och-lounger',
    getParentRoute: () => rootRouteImport,
  } as any)
const LosningarFineDiningRoute = LosningarFineDiningRouteImport.update({
  id: '/losningar/fine-dining',
  path: '/losningar/fine-dining',
  getParentRoute: () => rootRouteImport,
} as any)
const LosningarFristaendeRestaurangerRoute =
  LosningarFristaendeRestaurangerRouteImport.update({
    id: '/losningar/fristaende-restauranger',
    path: '/losningar/fristaende-restauranger',
    getParentRoute: () => rootRouteImport,
  } as any)
const LosningarHogvolymsverksamheterRoute =
  LosningarHogvolymsverksamheterRouteImport.update({
    id: '/losningar/hogvolymsverksamheter',
    path: '/losningar/hogvolymsverksamheter',
    getParentRoute: () => rootRouteImport,
  } as any)
const LosningarHotellRoute = LosningarHotellRouteImport.update({
  id: '/losningar/hotell',
  path: '/losningar/hotell',
  getParentRoute: () => rootRouteImport,
} as any)
const LosningarRestauranggrupperRoute =
  LosningarRestauranggrupperRouteImport.update({
    id: '/losningar/restauranggrupper',
    path: '/losningar/restauranggrupper',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analys': typeof AnalysRoute
  '/bokningsassistent': typeof BokningsassistentRoute
  '/bokningsregler': typeof BokningsreglerRoute
  '/bordsplacering': typeof BordsplaceringRoute
  '/epostagent': typeof EpostagentRoute
  '/gastinsikt': typeof GastinsiktRoute
  '/kampanjer': typeof KampanjerRoute
  '/salsplan': typeof SalsplanRoute
  '/tillganglighet': typeof TillganglighetRoute
  '/voice-agent': typeof VoiceAgentRoute
  '/losningar/barer-och-lounger': typeof LosningarBarerOchLoungerRoute
  '/losningar/fine-dining': typeof LosningarFineDiningRoute
  '/losningar/fristaende-restauranger': typeof LosningarFristaendeRestaurangerRoute
  '/losningar/hogvolymsverksamheter': typeof LosningarHogvolymsverksamheterRoute
  '/losningar/hotell': typeof LosningarHotellRoute
  '/losningar/restauranggrupper': typeof LosningarRestauranggrupperRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analys': typeof AnalysRoute
  '/bokningsassistent': typeof BokningsassistentRoute
  '/bokningsregler': typeof BokningsreglerRoute
  '/bordsplacering': typeof BordsplaceringRoute
  '/epostagent': typeof EpostagentRoute
  '/gastinsikt': typeof GastinsiktRoute
  '/kampanjer': typeof KampanjerRoute
  '/salsplan': typeof SalsplanRoute
  '/tillganglighet': typeof TillganglighetRoute
  '/voice-agent': typeof VoiceAgentRoute
  '/losningar/barer-och-lounger': typeof LosningarBarerOchLoungerRoute
  '/losningar/fine-dining': typeof LosningarFineDiningRoute
  '/losningar/fristaende-restauranger': typeof LosningarFristaendeRestaurangerRoute
  '/losningar/hogvolymsverksamheter': typeof LosningarHogvolymsverksamheterRoute
  '/losningar/hotell': typeof LosningarHotellRoute
  '/losningar/restauranggrupper': typeof LosningarRestauranggrupperRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analys': typeof AnalysRoute
  '/bokningsassistent': typeof BokningsassistentRoute
  '/bokningsregler': typeof BokningsreglerRoute
  '/bordsplacering': typeof BordsplaceringRoute
  '/epostagent': typeof EpostagentRoute
  '/gastinsikt': typeof GastinsiktRoute
  '/kampanjer': typeof KampanjerRoute
  '/salsplan': typeof SalsplanRoute
  '/tillganglighet': typeof TillganglighetRoute
  '/voice-agent': typeof VoiceAgentRoute
  '/losningar/barer-och-lounger': typeof LosningarBarerOchLoungerRoute
  '/losningar/fine-dining': typeof LosningarFineDiningRoute
  '/losningar/fristaende-restauranger': typeof LosningarFristaendeRestaurangerRoute
  '/losningar/hogvolymsverksamheter': typeof LosningarHogvolymsverksamheterRoute
  '/losningar/hotell': typeof LosningarHotellRoute
  '/losningar/restauranggrupper': typeof LosningarRestauranggrupperRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analys'
    | '/bokningsassistent'
    | '/bokningsregler'
    | '/bordsplacering'
    | '/epostagent'
    | '/gastinsikt'
    | '/kampanjer'
    | '/salsplan'
    | '/tillganglighet'
    | '/voice-agent'
    | '/losningar/barer-och-lounger'
    | '/losningar/fine-dining'
    | '/losningar/fristaende-restauranger'
    | '/losningar/hogvolymsverksamheter'
    | '/losningar/hotell'
    | '/losningar/restauranggrupper'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analys'
    | '/bokningsassistent'
    | '/bokningsregler'
    | '/bordsplacering'
    | '/epostagent'
    | '/gastinsikt'
    | '/kampanjer'
    | '/salsplan'
    | '/tillganglighet'
    | '/voice-agent'
    | '/losningar/barer-och-lounger'
    | '/losningar/fine-dining'
    | '/losningar/fristaende-restauranger'
    | '/losningar/hogvolymsverksamheter'
    | '/losningar/hotell'
    | '/losningar/restauranggrupper'
  id:
    | '__root__'
    | '/'
    | '/analys'
    | '/bokningsassistent'
    | '/bokningsregler'
    | '/bordsplacering'
    | '/epostagent'
    | '/gastinsikt'
    | '/kampanjer'
    | '/salsplan'
    | '/tillganglighet'
    | '/voice-agent'
    | '/losningar/barer-och-lounger'
    | '/losningar/fine-dining'
    | '/losningar/fristaende-restauranger'
    | '/losningar/hogvolymsverksamheter'
    | '/losningar/hotell'
    | '/losningar/restauranggrupper'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysRoute: typeof AnalysRoute
  BokningsassistentRoute: typeof BokningsassistentRoute
  BokningsreglerRoute: typeof BokningsreglerRoute
  BordsplaceringRoute: typeof BordsplaceringRoute
  EpostagentRoute: typeof EpostagentRoute
  GastinsiktRoute: typeof GastinsiktRoute
  KampanjerRoute: typeof KampanjerRoute
  SalsplanRoute: typeof SalsplanRoute
  TillganglighetRoute: typeof TillganglighetRoute
  VoiceAgentRoute: typeof VoiceAgentRoute
  LosningarBarerOchLoungerRoute: typeof LosningarBarerOchLoungerRoute
  LosningarFineDiningRoute: typeof LosningarFineDiningRoute
  LosningarFristaendeRestaurangerRoute: typeof LosningarFristaendeRestaurangerRoute
  LosningarHogvolymsverksamheterRoute: typeof LosningarHogvolymsverksamheterRoute
  LosningarHotellRoute: typeof LosningarHotellRoute
  LosningarRestauranggrupperRoute: typeof LosningarRestauranggrupperRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analys': {
      id: '/analys'
      path: '/analys'
      fullPath: '/analys'
      preLoaderRoute: typeof AnalysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bokningsassistent': {
      id: '/bokningsassistent'
      path: '/bokningsassistent'
      fullPath: '/bokningsassistent'
      preLoaderRoute: typeof BokningsassistentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bokningsregler': {
      id: '/bokningsregler'
      path: '/bokningsregler'
      fullPath: '/bokningsregler'
      preLoaderRoute: typeof BokningsreglerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bordsplacering': {
      id: '/bordsplacering'
      path: '/bordsplacering'
      fullPath: '/bordsplacering'
      preLoaderRoute: typeof BordsplaceringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epostagent': {
      id: '/epostagent'
      path: '/epostagent'
      fullPath: '/epostagent'
      preLoaderRoute: typeof EpostagentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gastinsikt': {
      id: '/gastinsikt'
      path: '/gastinsikt'
      fullPath: '/gastinsikt'
      preLoaderRoute: typeof GastinsiktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kampanjer': {
      id: '/kampanjer'
      path: '/kampanjer'
      fullPath: '/kampanjer'
      preLoaderRoute: typeof KampanjerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salsplan': {
      id: '/salsplan'
      path: '/salsplan'
      fullPath: '/salsplan'
      preLoaderRoute: typeof SalsplanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tillganglighet': {
      id: '/tillganglighet'
      path: '/tillganglighet'
      fullPath: '/tillganglighet'
      preLoaderRoute: typeof TillganglighetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice-agent': {
      id: '/voice-agent'
      path: '/voice-agent'
      fullPath: '/voice-agent'
      preLoaderRoute: typeof VoiceAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/losningar/barer-och-lounger': {
      id: '/losningar/barer-och-lounger'
      path: '/losningar/barer-och-lounger'
      fullPath: '/losningar/barer-och-lounger'
      preLoaderRoute: typeof LosningarBarerOchLoungerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/losningar/fine-dining': {
      id: '/losningar/fine-dining'
      path: '/losningar/fine-dining'
      fullPath: '/losningar/fine-dining'
      preLoaderRoute: typeof LosningarFineDiningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/losningar/fristaende-restauranger': {
      id: '/losningar/fristaende-restauranger'
      path: '/losningar/fristaende-restauranger'
      fullPath: '/losningar/fristaende-restauranger'
      preLoaderRoute: typeof LosningarFristaendeRestaurangerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/losningar/hogvolymsverksamheter': {
      id: '/losningar/hogvolymsverksamheter'
      path: '/losningar/hogvolymsverksamheter'
      fullPath: '/losningar/hogvolymsverksamheter'
      preLoaderRoute: typeof LosningarHogvolymsverksamheterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/losningar/hotell': {
      id: '/losningar/hotell'
      path: '/losningar/hotell'
      fullPath: '/losningar/hotell'
      preLoaderRoute: typeof LosningarHotellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/losningar/restauranggrupper': {
      id: '/losningar/restauranggrupper'
      path: '/losningar/restauranggrupper'
      fullPath: '/losningar/restauranggrupper'
      preLoaderRoute: typeof LosningarRestauranggrupperRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysRoute: AnalysRoute,
  BokningsassistentRoute: BokningsassistentRoute,
  BokningsreglerRoute: BokningsreglerRoute,
  BordsplaceringRoute: BordsplaceringRoute,
  EpostagentRoute: EpostagentRoute,
  GastinsiktRoute: GastinsiktRoute,
  KampanjerRoute: KampanjerRoute,
  SalsplanRoute: SalsplanRoute,
  TillganglighetRoute: TillganglighetRoute,
  VoiceAgentRoute: VoiceAgentRoute,
  LosningarBarerOchLoungerRoute: LosningarBarerOchLoungerRoute,
  LosningarFineDiningRoute: LosningarFineDiningRoute,
  LosningarFristaendeRestaurangerRoute: LosningarFristaendeRestaurangerRoute,
  LosningarHogvolymsverksamheterRoute: LosningarHogvolymsverksamheterRoute,
  LosningarHotellRoute: LosningarHotellRoute,
  LosningarRestauranggrupperRoute: LosningarRestauranggrupperRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
