/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BokningsassistentRouteImport } from './routes/bokningsassistent'
import { Route as BokningsreglerRouteImport } from './routes/bokningsregler'
import { Route as BordsplaceringRouteImport } from './routes/bordsplacering'
import { Route as EpostagentRouteImport } from './routes/epostagent'
import { Route as SalsplanRouteImport } from './routes/salsplan'
import { Route as TillganglighetRouteImport } from './routes/tillganglighet'
import { Route as VoiceAgentRouteImport } from './routes/voice-agent'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BokningsassistentRoute = BokningsassistentRouteImport.update({
  id: '/bokningsassistent',
  path: '/bokningsassistent',
  getParentRoute: () => rootRouteImport,
} as any)
const BokningsreglerRoute = BokningsreglerRouteImport.update({
  id: '/bokningsregler',
  path: '/bokningsregler',
  getParentRoute: () => rootRouteImport,
} as any)
const BordsplaceringRoute = BordsplaceringRouteImport.update({
  id: '/bordsplacering',
  path: '/bordsplacering',
  getParentRoute: () => rootRouteImport,
} as any)
const EpostagentRoute = EpostagentRouteImport.update({
  id: '/epostagent',
  path: '/epostagent',
  getParentRoute: () => rootRouteImport,
} as any)
const SalsplanRoute = SalsplanRouteImport.update({
  id: '/salsplan',
  path: '/salsplan',
  getParentRoute: () => rootRouteImport,
} as any)
const TillganglighetRoute = TillganglighetRouteImport.update({
  id: '/tillganglighet',
  path: '/tillganglighet',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceAgentRoute = VoiceAgentRouteImport.update({
  id: '/voice-agent',
  path: '/voice-agent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bokningsassistent': typeof BokningsassistentRoute
  '/bokningsregler': typeof BokningsreglerRoute
  '/bordsplacering': typeof BordsplaceringRoute
  '/epostagent': typeof EpostagentRoute
  '/salsplan': typeof SalsplanRoute
  '/tillganglighet': typeof TillganglighetRoute
  '/voice-agent': typeof VoiceAgentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bokningsassistent': typeof BokningsassistentRoute
  '/bokningsregler': typeof BokningsreglerRoute
  '/bordsplacering': typeof BordsplaceringRoute
  '/epostagent': typeof EpostagentRoute
  '/salsplan': typeof SalsplanRoute
  '/tillganglighet': typeof TillganglighetRoute
  '/voice-agent': typeof VoiceAgentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bokningsassistent': typeof BokningsassistentRoute
  '/bokningsregler': typeof BokningsreglerRoute
  '/bordsplacering': typeof BordsplaceringRoute
  '/epostagent': typeof EpostagentRoute
  '/salsplan': typeof SalsplanRoute
  '/tillganglighet': typeof TillganglighetRoute
  '/voice-agent': typeof VoiceAgentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bokningsassistent'
    | '/bokningsregler'
    | '/bordsplacering'
    | '/epostagent'
    | '/salsplan'
    | '/tillganglighet'
    | '/voice-agent'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bokningsassistent'
    | '/bokningsregler'
    | '/bordsplacering'
    | '/epostagent'
    | '/salsplan'
    | '/tillganglighet'
    | '/voice-agent'
  id:
    | '__root__'
    | '/'
    | '/bokningsassistent'
    | '/bokningsregler'
    | '/bordsplacering'
    | '/epostagent'
    | '/salsplan'
    | '/tillganglighet'
    | '/voice-agent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BokningsassistentRoute: typeof BokningsassistentRoute
  BokningsreglerRoute: typeof BokningsreglerRoute
  BordsplaceringRoute: typeof BordsplaceringRoute
  EpostagentRoute: typeof EpostagentRoute
  SalsplanRoute: typeof SalsplanRoute
  TillganglighetRoute: typeof TillganglighetRoute
  VoiceAgentRoute: typeof VoiceAgentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bokningsassistent': {
      id: '/bokningsassistent'
      path: '/bokningsassistent'
      fullPath: '/bokningsassistent'
      preLoaderRoute: typeof BokningsassistentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bokningsregler': {
      id: '/bokningsregler'
      path: '/bokningsregler'
      fullPath: '/bokningsregler'
      preLoaderRoute: typeof BokningsreglerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bordsplacering': {
      id: '/bordsplacering'
      path: '/bordsplacering'
      fullPath: '/bordsplacering'
      preLoaderRoute: typeof BordsplaceringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epostagent': {
      id: '/epostagent'
      path: '/epostagent'
      fullPath: '/epostagent'
      preLoaderRoute: typeof EpostagentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salsplan': {
      id: '/salsplan'
      path: '/salsplan'
      fullPath: '/salsplan'
      preLoaderRoute: typeof SalsplanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tillganglighet': {
      id: '/tillganglighet'
      path: '/tillganglighet'
      fullPath: '/tillganglighet'
      preLoaderRoute: typeof TillganglighetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice-agent': {
      id: '/voice-agent'
      path: '/voice-agent'
      fullPath: '/voice-agent'
      preLoaderRoute: typeof VoiceAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BokningsassistentRoute: BokningsassistentRoute,
  BokningsreglerRoute: BokningsreglerRoute,
  BordsplaceringRoute: BordsplaceringRoute,
  EpostagentRoute: EpostagentRoute,
  SalsplanRoute: SalsplanRoute,
  TillganglighetRoute: TillganglighetRoute,
  VoiceAgentRoute: VoiceAgentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
